# Generated by Django 6.1.1 on 2026-09-14 03:18
# ruff: noqa: RUF012

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import chores.models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, validators=[chores.models.validate_chore_name]
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("biweekly", "Biweekly")],
                        max_length=8,
                    ),
                ),
                ("cadence_anchor", models.DateField(blank=True, null=True)),
                (
                    "start_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal(0))
                        ],
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chores",
                        to="chores.household",
                    ),
                ),
            ],
        ),
    ]
