# Generated by Django 6.1.1 on 2026-09-14 03:44
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models

import chores.models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0002_chore"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_done_at",
                    models.DateTimeField(
                        validators=[chores.models.validate_aware_datetime]
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_histories",
                        to="chores.chore",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_histories",
                        to="chores.resident",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resident", "chore"),
                        name="unique_completion_history_resident_chore",
                    )
                ],
            },
        ),
    ]
