# Generated by Django 6.1.1 on 2026-09-14 04:02
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0003_completionhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="chores.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("bounty", "Bounty"),
                            ("claimed", "Claimed"),
                            ("done", "Done"),
                        ],
                        max_length=8,
                    ),
                ),
                ("deadline", models.DateField()),
                ("listed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="chores.chore",
                    ),
                ),
                (
                    "current_holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="held_slots",
                        to="chores.resident",
                    ),
                ),
                (
                    "original_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_slots",
                        to="chores.resident",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="chores.period",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("household", "start_date"),
                name="unique_period_household_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.UniqueConstraint(
                fields=("period", "chore"), name="unique_slot_period_chore"
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("assigned", "bounty", "claimed", "done"))
                ),
                name="slot_status_is_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_holder", models.F("original_assignee")),
                        ("listed_at__isnull", True),
                        ("status", "assigned"),
                    ),
                    models.Q(
                        ("current_holder__isnull", True),
                        ("listed_at__isnull", False),
                        ("status", "bounty"),
                    ),
                    models.Q(
                        ("current_holder__isnull", False),
                        ("listed_at__isnull", False),
                        ("status", "claimed"),
                        models.Q(
                            ("current_holder", models.F("original_assignee")),
                            _negated=True,
                        ),
                    ),
                    models.Q(("current_holder__isnull", False), ("status", "done")),
                    _connector="OR",
                ),
                name="slot_status_state_invariants",
            ),
        ),
    ]
