# Generated by Django 6.1.1 on 2026-09-14 08:00
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0004_period_slot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_slots",
                to="chores.resident",
            ),
        ),
    ]
