# Generated by Django 6.1.1 on 2026-09-14 07:36
# ruff: noqa: RUF012, FURB157

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import chores.models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0005_slot_completed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="IOU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        validators=[chores.models.validate_claimed_at]
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ious_as_creditor",
                        to="chores.resident",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ious_as_debtor",
                        to="chores.resident",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="iou",
                        to="chores.slot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("debtor", models.F("creditor")), _negated=True
                        ),
                        name="iou_debtor_differs_creditor",
                    )
                ],
            },
        ),
    ]
