# Generated by Django 6.1.1 on 2026-09-19 11:07
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0006_iou"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chore",
            name="cadence",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Biweekly"),
                    ("one_off", "One-off"),
                ],
                max_length=8,
            ),
        ),
    ]
