# Generated by Django 6.1.1 on 2026-09-19 11:20
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0007_chore_due_date_and_one_off_cadence"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="left_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
